const allItems = [
  { id: 1, name: "Coração De Quartzo", img: "./../img/jogo/itens/Vida2.png", desc: "+40 HP" },
  { id: 2, name: "Gerador De Algas", img: "./../img/jogo/itens/Algas.png", desc: "+1 ENERGIA" },
  { id: 3, name: "ReeForja", img: "./../img/jogo/itens/Picareta2.png", desc: "Ganhe 15🪙 extras ao derrotar elites e inimigos comuns. Ganhe agora +45🪙." },
  { id: 4, name: "Chip Do Batedor", img: "./../img/jogo/itens/auraLaranja.png", desc: "+1 ENERGIA" },
  { id: 5, name: "Amuleto De Gaea", img: "./../img/jogo/itens/colarDeGaea.png", desc: "+50 HP, +1 ENERGIA" },
  { id: 6, name: "Ecosistema Preservado", img: "./../img/jogo/itens/bolhaPreservada.png", desc: "+50 HP, +1 ENERGIA" },
  { id: 7, name: "Preservar", img: "./../img/jogo/itens/ecosistema.png", desc: "+40 HP" },
  { id: 8, name: "Chip Do Defensor", img: "./../img/jogo/itens/chipDeDef.png", desc: "+10 ARMADURA TODO TURNO" },
  { id: 9, name: "Pedras De Mana", img: "./../img/jogo/itens/pedrasDeMana.png", desc: "+1 ENERGIA" },
  { id: 10, name: "Cartas Runicas", img: "./../img/jogo/itens/versoCard.png", desc: "+1 CARTA NA MÃO (max 10)" },
  { id: 11, name: "Carta Amaldiçoada", img: "./../img/jogo/itens/cartaTriste.png", desc: "-1 CARTA NA MÃO" },
  { id: 12, name: "Olho Do Kraken", img: "./../img/jogo/itens/olhoKraken.png", desc: "Sempre que uma carta VERMELHA/ATTACK for usada cause 5 de dano em todos os inimigos" },
  { id: 13, name: "Olho De lizdris", img: "./../img/jogo/itens/olhoIlizdris.png", desc: "Sempre que uma carta AZUL/DEFESA for usada ganhe 5 de escudo nesse turno" },
  { id: 14, name: "Marujin", img: "./../img/jogo/itens/marujin.png", desc: "+10 HP, +5 ARMADURA TODO TURNO, +1 ENERGIA" },
  { id: 15, name: "Reciclador", img: "./../img/jogo/itens/colarReciclagem.png", desc: "Todas as cartas elementais que MARCAM o inimigo causam dano ao primeiro inimigo igual a 5% de todo o lixo reciclado (arredonda para baixo)" },
  { id: 16, name: "Ganacia", img: "./../img/jogo/itens/ouro.png", desc: "Todas as cartas elementais que MARCAM o inimigo causam dano ao primeiro inimigo igual a 10% de todo o 🪙 (arredonda para baixo)" },
  { id: 17, name: "Coroa Glacial", img: "./../img/jogo/itens/leryGo.png", desc: "Todas as cartas de GELO/FROST tem 30% de chance de causar 20% de todo o lixo reciclado como dano ao primeiro inimigo" },
  { id: 18, name: "Estatua Da Gaea", img: "./../img/jogo/itens/estatuaDeGaea.png", desc: "Todas as cartas do tipo LIXO agora quando usadas dão +5🪙 e aumentão o contador de lixo reciclado em +1" },
  { id: 19, name: "Coroa Da Gaea", img: "./../img/jogo/itens/coroaDeGaea.png", desc: "Se você tiver a Estatua De Gaea e o Amuleto De Gaea, sempre que uma carta for usada cure 2 de vida" },
  { id: 20, name: "Reciclagem Elemental", img: "./../img/jogo/itens/reciclagemElemental.png", desc: "Todas as cartas elementais a partir de agora sempre que usadas aumentão o contador de lixo reciclado em +2" },
  { id: 21, name: "Gaeazinha", img: "./../img/jogo/itens/peluciaDeGaea.png", desc: "Aumenta as opções de itens em +1" },
  { id: 22, name: "Capsula Médica", img: "./../img/jogo/itens/reatorMedico.png", desc: "Precisa de um Gerador para funcionar. Sempre que uma carta VERDE/BUFF for usada tem 30% de chance de ganhar 1 de energia nesse turno" },
  { id: 23, name: "Kit Médico", img: "./../img/jogo/itens/kitMedico.png", desc: "No final de cada combate cure 10% da sua vida maxima" },
  { id: 24, name: "Chip Do Curandeiro", img: "./../img/jogo/itens/chipDeCura.png", desc: "Precisa de um Gerador para funcionar. Sempre que uma carta VERDE/BUFF for usada cure 2 de vida" },
  { id: 25, name: "Gerador", img: "./../img/jogo/itens/gerador.png", desc: "+1 ENERGIA e energiza itens" },
  { id: 26, name: "Fragmento Do Mundo", img: "./../img/jogo/itens/frostKey.png", desc: "Essa chave peculiar parece ser feita de gelo luminezente, será que ela possui alguma utilidade? ela aparenta estar ligada com solice, será que ela diz algo?" },
  { id: 27, name: "Coração Do Mundo", img: "./../img/jogo/itens/fireKey.png", desc: "Essa chave esta muito quenta para segurar, talves algo feito de gelo luminezente esfrie" },
  { id: 28, name: "Cavalo Guia", img: "./../img/jogo/itens/cavalo.png", desc: "Tem chance do boss Belinda aparecer para recuperar esse item na zona 4. +1 ENERGIA" },
  { id: 29, name: "Baralho Magico", img: "./../img/jogo/itens/baralhoMagico.png", desc: "Tem chance do boss Svetlana aparecer para recuperar esse item na zona 4. +1 CARTA NA MÃO (max 10)" },
  { id: 30, name: "Detector De Radiação", img: "./../img/jogo/itens/detectorRadio.png", desc: "Tem chance do boss Pedro aparecer para recuperar esse item na zona 2. +1 ENERGIA e -1 CARTA NA MÃO" },
  { id: 31, name: "Medalha De Herói", img: "./../img/jogo/itens/heroi.png", desc: "Tem chance do boss Guinevere aparecer para recuperar esse item na zona 1. +100 HP" },
  { id: 32, name: "Reflexo Da Verdade", img: "./../img/jogo/itens/sombraDoPassado.png", desc: "Tem chance do boss Isla aparecer para recuperar esse item na zona 2. +10 ARMADURA TODO TURNO" },
  { id: 33, name: "Óculos Supimpa", img: "./../img/jogo/itens/peruEsterminador.png", desc: "Tem chance do boss Peru aparecer para recuperar esse item na zona 1. +40 HP" },
  { id: 34, name: "Aureola Dos Mortos", img: "./../img/jogo/itens/coroaDosMortos.png", desc: "Uma linda replica, quem será que tem a original? +100 HP" },
  { id: 35, name: "Infância Manchada", img: "./../img/jogo/itens/tybers.png", desc: "Tem uma etiqueta escrito que pertence a \"Alegria\". +10 ARMADURA TODO TURNO" },
  { id: 36, name: "Guia Da Alma", img: "./../img/jogo/itens/lampiao.png", desc: "Revela a \"verdade\", esse item precissa de mais 2 outros itens para ativar seu potencial? Seja lá qual for, em seu metal está escrito \"Traição\". +1 ENERGIA" },
  { id: 37, name: "Sorte Elemental", img: "./../img/jogo/itens/sorteElemental.png", desc: "Todas as cartas elementais tem uma chance de aparecer MUITO maior." },
  { id: 38, name: "Album Velho", img: "./../img/jogo/itens/albumVelho.png", desc: "Diminui drasticamente a chance de aparecer cartas comuns." },
  { id: 39, name: "Album De Coleção", img: "./../img/jogo/itens/albumMagico.png", desc: "Cartas épicas, lendárias e cintilante tem uma chance maior de aparecer." },
  { id: 40, name: "Ás De Copas", img: "./../img/jogo/itens/cartaDaSorte.png", desc: "Diminui a chance de aparecer cartas comuns e raras, e aumenta a chance de cartas épicas e lendárias." },
  { id: 41, name: "Cripto", img: "./../img/jogo/itens/criptoGaea.png", desc: "Aumenta o dinheiro 🪙 recebido em 50% em batalhas. Ganhe agora +45🪙." },
  { id: 42, name: "Investimento", img: "./../img/jogo/itens/investimento.png", desc: "Ganhe 35🪙 extras ao derrotar um boss. Ganhe agora +45🪙." },
];